### PR TITLE
Create Hello.txt

### PR DESCRIPTION
**Pull request by Hrushi20**

### CODE REVIEW

**Review by supreeth-patrudu — COMMENTED** [review]
Hello Unknown Friend...I Would be happy to help you
No I didn't start minor project was hoping you would do it for me

Full biscuit ra...u always say you didn't do shit

Your's sincerely
Other Unknown Friend.

**Comment by Hrushi20** [comment]
I am not very good at programming mate. I guess we can collaborate on the project and get this done. 
I am not sure what you mean by biscuits. Waiting for a better explanation.

Yours Friendly,
The Lost Unknown Friend you'll never find.

**Comment by supreeth-patrudu** [comment]
I should be the one who says "i'm not good at programming"
Have any ideas on the project i'll be happy to help 
biscuit means topper

Yours Faithfully,
Friend who is trying to find Lost Unknown Friend.

**Comment by Hrushi20** [comment]
Hello Friend who is trying to find Lost Unknown Friend,

You say you aren't good at programming but doing great in your college. Waiting for you to pitch sm ideas to have a good minor project. 
All kinds of humans eat biscuits😋😋😋

Yours sincerely 
The Friend who can't be found.

**Comment by supreeth-patrudu** [comment]
Heey The Friend who can't be found,

I won't give up on finding you...I know a person in my class called Hrushikesh (roll no.512 not the other Hrushikesh) 
He's the class topper, i'll take his help😁😁.
Hope we can collaborate in the near future...Waiting for your REVOLUTIONARY ideas
Ohh... i thought only toppers eat biscuits

Yours Friendly,
The Friend who will find The Friend who can't be found

**Comment by Hrushi20** [comment]
Hello Friend,
Stop finding me. It's close to impossible. Also can you merge this pull request into your code base. During this process you'll learn what a Pull Request is on github.

Yours friendly,
Idk who am I.

**Comment by supreeth-patrudu** [comment]
Dude...If I accept this merge request ...then can people read these comments?

**Comment by supreeth-patrudu** [comment]
> Hello Friend, Stop finding me. It's close to impossible. Also can you merge this pull request into your code base. During this process you'll learn what a Pull Request is on github.
> 
> Yours friendly, Hrushikesh Rao

PS: you just revealed your name...

**Comment by Hrushi20** [comment]
People can already read these comments. Its completely open. That's the beauty of open source. You can contribute and anybody with solution can help you out. You repository is public hence every1 can read it if they visit this link.

**Comment by Hrushi20** [comment]
I don't see my name. Are you hacking github???

**Pull request merged**
